server:
  port: 8087

spring:
  application:
    name: spring-cloud-config-client
management:
  endpoints:
    web:
      exposure:
        include: ["*"] #暴露一个refresh端点，需要手动调用。post：http://localhost:8080/actuator/refresh




