server:
  port: 8082
spring:
  application:
    name: lavender-service-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*' # yml配置需要加单引号；properties配置直接用 * 即可。
  endpoint:
    health:
      show-details: always