server:
  port: 8088

spring:
  application:
    name: lavender-config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:C:/Users/zhuchen8/Desktop/conf #由于git比较麻烦，因此使用本地的文件来进行模拟，需要在桌面的conf文件下加一个zhuchen-dev.properties文件来进行模拟
          # 访问配置路径：http://localhost:8081/zhuchen/dev 。 直接获取配置文件中的内容：http://localhost:8081/zhuchen-dev.properties
  profiles:
    active: native #本地文件

management:
  endpoints:
    web:
      exposure:
        include: '*'