server:
  port: 8087

spring:
  application:
    name: lavender-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhuchen-heavy/lavender-spring-cloud.git
          search-paths: data
          username: 834434471@qq.com
          password: Zc940309
      label: master

